spring:
  profiles:
    active: worker

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    ssl:
      enabled: false

logging:
  level:
    org: INFO

tutorial:
  client:
    duration: 10000

app:
  rabbitmq:
    exchangeName: anonymization
